### ISSUE TITLE
The DiSEA Dashboard is loading.

### ISSUE THREAD

**Issue by Buda9** [ild-thl/moodle-block_disealytics#19]
Hi there. From what I read in readme, this is one amazing plugin, thank you for creating it. However, I'm still trying to understand how it works? I've already uploaded 2 csv files, but when I add block to course all I see is a message "The DiSEA Dashboard is loading.". Perhaps you could shed some light on this? Thank you

![Screenshot_211](https://github.com/ild-thl/moodle-block_disealytics/assets/1422662/7ac2a737-5257-46bf-99d6-e1239064a1c4)

**Comment by Buda9** [comment]
issue with my theme, not related to plugin

**Comment by jmorrph** [comment]
Thanks for coming back this. Even if the problem is resolved for you, you creating this issue sparked some conversation in the team regarding the Moodle/database/php versions we want to support. Clarifying these requirements in our readme is on our radar now. So even if we could not really help you (I am sorry it took a while to reply), thank you for reporting in the first place!
